services:
  - type: web
    name: mpesa-fraud-detection-system
    runtime: python
    rootDir: inference
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
      - key: APP_ENV
        value: production
    plan: free
    autoDeploy: true
  